GET http://localhost:3000/api/members

###

GET http://localhost:3000/api/members/60e5a825f8c0be459c374e06

###

POST http://localhost:3000/api/members
Content-Type: application/json

{
    "name": "Shahab Athar",
}

###

DELETE http://localhost:3000/api/members/60e5a825f8c0be459c374e06